# Generated by Django 6.0.6 on 2026-07-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0003_hall_unique_hall_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('standart', 'Standart'), ('comfort', 'Comfort'), ('vip', 'Vip')], default='Standart')),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hall.hall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
