# Generated by Django 6.0.6 on 2026-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
