# Generated by Django 6.0.6 on 2026-07-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='reference_id',
            field=models.CharField(default='e2626e1c', editable=False, max_length=8, null=True, unique=True),
        ),
    ]
