# Generated by Django 6.0.6 on 2026-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='reference_id',
            field=models.CharField(default='01711a52', editable=False, max_length=8, null=True, unique=True),
        ),
    ]
