# Generated by Django 6.0.6 on 2026-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='reference_id',
            field=models.CharField(default='a95fcde0', editable=False, max_length=8, null=True, unique=True),
        ),
    ]
