# Generated by Django 6.0.6 on 2026-07-02 14:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('small_description', models.CharField(blank=True, null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('duration', models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(days=1))])),
                ('age_available', models.CharField(choices=[('0', '0+'), ('6', '6+'), ('12', '12+'), ('16', '16+'), ('18', '18+')])),
                ('category', models.CharField(choices=[('theater', 'Theater'), ('cinema', 'Cinema'), ('other', 'Other')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
