# Generated by Django 6.0.6 on 2026-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_name'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='uniqe name for created_by'),
        ),
    ]
