# Generated by Django 6.0.6 on 2026-07-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_venue_uniqe_name_for_created_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venue',
            name='uniqe name for created_by',
        ),
    ]
