# Generated by Django 6.0.6 on 2026-07-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_name'),
        ('venue', '0003_remove_venue_uniqe_name_for_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_venue_name_per_address'),
        ),
    ]
