# Generated by Django 6.0.6 on 2026-07-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_name'),
        ('venue', '0004_rename_adress_venue_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='site_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
