# Generated by Django 6.0.6 on 2026-07-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('number', models.PositiveSmallIntegerField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venus', to='venue.venue')),
            ],
        ),
    ]
