# Generated by Django 6.0.6 on 2026-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_hall_name'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hall',
            constraint=models.UniqueConstraint(fields=('venue', 'number'), name='unique_hall_venue'),
        ),
    ]
