# Generated by Django 6.0.6 on 2026-07-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('hall', '0003_hall_unique_hall_venue'),
        ('seat', '0002_seat_number'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_sessions', to='hall.hall')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_sessions', to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SeatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('free', 'Free'), ('pending', 'Pending'), ('busy', 'Busy')], default='free')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('event_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='session.eventsession')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seat.seat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventsession',
            constraint=models.UniqueConstraint(fields=('event', 'venue', 'hall', 'timestamp'), name='Unique session in definitely place and time'),
        ),
        migrations.AddConstraint(
            model_name='seatsession',
            constraint=models.UniqueConstraint(fields=('event_session', 'seat'), name='Unique SeatSession in definitely event_session'),
        ),
    ]
