# Generated by Django 6.0.6 on 2026-07-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='user and seat_session must be unique.',
        ),
    ]
