# Generated by Django 6.0.6 on 2026-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_user_and_seat_session_must_be_unique_'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='draft_expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
