# Generated by Django 6.0.6 on 2026-07-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_booking_draft_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft')),
                ('payment_id', models.UUIDField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
